name: 🐞 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "status/needs-triage"]

body:
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |-
        1. What command are you running?
        2. Cloud provider you are launching
        3. Environment you have, like single account, multi-account, organizations, multi or single subscription, etc.
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result with Screenshots or Logs
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: How did you install yriser?
      options:
        - Cloning the repository from github.com (git clone)
        - Shell exec (./yriser)
        - Docker (docker pull czantoine/yriser)
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Resource
      description: From where are you running yriser?
      placeholder: |-
        1. EC2 instance
        2. Fargate task
        3. Docker container locally
        4. EKS
        5. Cloud9
        6. CodeBuild
        7. Workstation
        8. Other(please specify)
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: OS used
      description: Which OS are you using?
      placeholder: |-
        1. Amazon Linux 2
        2. MacOS
        3. Docker
        4. Windows
        5. Other(please specify)
    validations:
      required: true
  - type: input
    id: yriser-version
    attributes:
      label: yriser version
      description: Which yriser version are you using?
      placeholder: |-
        yriser --version
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      description: Additional context
      label: Context
    validations:
      required: false